# Generated by Django 4.2.4 on 2023-11-30 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_chat_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
    ]
