# Generated by Django 4.2.4 on 2023-12-08 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_user_has_sent_request_user_is_read_user_request_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_read',
            new_name='is_friend',
        ),
    ]
