# Generated by Django 4.2.4 on 2023-12-08 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_rename_is_read_user_is_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pfp',
            field=models.ImageField(default='default.jpeg', upload_to='profile-pictures'),
        ),
    ]
