# Generated by Django 4.2.4 on 2023-11-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_bids_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to='auctions.listings'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='startprice',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
