# Generated by Django 4.2.4 on 2023-11-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_user_watchlist_alter_listings_startprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='highestbid',
            field=models.IntegerField(default=0),
        ),
    ]
