# Generated by Django 4.2.4 on 2023-11-12 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listings_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='highestbid',
        ),
        migrations.RemoveField(
            model_name='listings',
            name='total_bids',
        ),
    ]
