# Generated by Django 4.2.4 on 2023-11-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auctions',
            field=models.ManyToManyField(blank=True, related_name='auctions', to='auctions.listings'),
        ),
    ]
