# Generated by Django 4.2.4 on 2023-11-13 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_listings_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='highestbid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auctions.bids'),
        ),
    ]
