# Generated by Django 4.2.4 on 2023-11-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_remove_user_balance_remove_user_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
